name: 'Slack alerts for Security Alerts'
on: [push]
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      # X.X.X - Latest version available at: https://github.com/kunalnagarco/action-cve/releases
      - name: Checkout
        uses: actions/checkout@v3
      - uses: kunalnagarco/action-cve@v1.6.14
        with:
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          slack_webhook: ${{ secrets.SLACK_WEBHOOK }}
          count: 20
