name: grype
on: push
jobs:
  grype:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build Image
        run : docker build -t dvna .
      - name: Scan Image 
        id: scan
        uses: anchore/scan-action@v2
        with:
           image: "dvna"
           acs-report-enable: true
      - name: Upload the scan using codeql-sarif uplaod
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: ${{ steps.scan.outputs.sarif }}
      
    
