name: grype
on: push
jobs:
  grype:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build Image
        run : docker build -t dvna .
      - name: Scan Image 
        uses: anchore/scan-action@v2
        with:
           image: "dvna"
      
    
