name: Dependapager
on:
  schedule:
    - cron: "0 0 * * 1"
  workflow_dispatch:

jobs:
  Depedapager:
    uses: pwned-17/security-workflows/.github/workflows/dependapager.yml@main
    secrets:
      PERSONAL_ACCESS_TOKEN: ${{secrets.PERSONAL_ACCESS_TOKEN}}
      SLACK_TOKEN: ${{secrets.SLACK_TOKEN}}
      JIRA_API_TOKEN: ${{secrets.JIRA_API_TOKEN}} 
    
        
          
