name: Snyk Scan 
on:
  workflow_dispatch:
jobs:
  snyk:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: run Npm build
        run: npm install
      - name: Run synk Scan
        uses: snyk/actions/node@master
        env:
          SNYK_TOKEN: ${{secrets.SNYK_TOKEN}}
