name: Snyk Scan 
on: [push,pull_request]
jobs:
  snyk:
    runs-on: ubuntu-latest
    steps:
      -uses: actions/checkout@master
      -name: Run synk Scan 
       uses: snyk/actions/node@master
       env:
         -SNYK_TOKEN: ${{secrets.SNYK_TOKEN}}
       with:
         command: monitor
