name: ' Dependabot V2 Alerts'
on:
  workflow_dispatch:
env:
    JIRA_BASE_URL: https://agrevolution.atlassian.net/
    JIRA_USER_EMAIL: shaik.ajmal@agrevolution.in
    JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
    JIRA_PROJECT: INC
    JIRA_ISSUE_TYPE: Task

jobs:
  #Send-Slack-Alerts:
  #  runs-on: ubuntu-latest
  #  steps:
  #    # X.X.X - Latest version available at: https://github.com/kunalnagarco/action-cve/releases
  #    - name: Checkout
  #      uses: actions/checkout@v3
  #   - name: Depebdabot-Slack Alerts
  #     uses: pwned-17/dependabot-slack@v1.6.16
  #      with:
  #        token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
  #        slack_webhook: ${{ secrets.SLACK_WEBHOOK }}
  #        count: 20

  create-jira:
      name: Dependabot Jira
      runs-on: ubuntu-latest
      steps:
      - name: Check Dependabot Alerts
        id: alerts
        uses: pwned-17/check-dependabot@v1.2.8
        with:
          github_personal_token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}  
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Create Tickets
        if: ${{ (steps.alerts.outputs.critical_alerts > 0) || (steps.alerts.outputs.high_alerts > 0) }}
        env:
          TOTAL_ALERTS: ${{ steps.alerts.outputs.total_alerts }}
          REPO_URL: ${{ steps.alerts.outputs.repo_url }}
          JIRA_BASE_URL: ${{ env.JIRA_BASE_URL }}
          JIRA_USER_EMAIL: ${{ env.JIRA_USER_EMAIL }}
          JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
        uses: atlassian/gajira-login@v2.0.0

      - name: Create Jira Issue
        if: ${{ (steps.alerts.outputs.critical_alerts > 0) || (steps.alerts.outputs.high_alerts > 0) }}
        id: create
        uses: atlassian/gajira-create@v2.0.1
        with:
          project: ${{ env.JIRA_PROJECT }}
          issuetype: ${{ env.JIRA_ISSUE_TYPE }}
          summary: |
            Depenbdabot Alerts [ ${{ steps.alerts.outputs.repo_name }} ]
            
              
          description: |
             Critical and High Vulnerabilites reported by Depebdabot
              ${{ steps.alerts.outputs.summary }}
