name: ' Dependabot V2 Alerts'
on:
  workflow_dispatch:
env:
    JIRA_BASE_URL: https://agrevolution.atlassian.net/
    JIRA_USER_EMAIL: shaik.ajmal@agrevolution.in
    JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
    JIRA_PROJECT: INC
    JIRA_ISSUE_TYPE: Task

jobs:
  Send-Slack-Alerts:
     runs-on: ubuntu-latest
     steps:
  #    # X.X.X - Latest version available at: https://github.com/kunalnagarco/action-cve/releases
      - name: Checkout
        uses: actions/checkout@v3
      - name: Depebdabot-Slack Alerts
        uses: pwned-17/dependabot-slack@v1.6.16
        with:
           token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
           slack_webhook: ${{ secrets.SLACK_WEBHOOK }}
           count: 20

  create-jira:
      name: Dependabot Jira
      runs-on: ubuntu-latest
      steps:
      - name: Check Dependabot Alerts
        id: alerts
        uses: pwned-17/check-dependabot@v1.2.9
        with:
          github_personal_token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}  
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Create Tickets
        if: ${{ (steps.alerts.outputs.critical_alerts > 0) || (steps.alerts.outputs.high_alerts > 0) }}
        env:
          JIRA_BASE_URL: ${{ env.JIRA_BASE_URL }}
          JIRA_USER_EMAIL: ${{ env.JIRA_USER_EMAIL }}
          JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
        uses: atlassian/gajira-login@v2.0.0

      - name: Create Jira Issue
        if: ${{ (steps.alerts.outputs.critical_alerts > 0) || (steps.alerts.outputs.high_alerts > 0) }}
        id: create
        uses: atlassian/gajira-create@v2.0.1
        with:
          project: ${{ env.JIRA_PROJECT }}
          issuetype: ${{ env.JIRA_ISSUE_TYPE }}
          summary: |
            Open Depenbdabot Alerts for [ ${{ steps.alerts.outputs.repo_name }} ]
            
              
          description: |
               There are currently ${{ steps.alerts.outputs.total_alerts }} dependabot alerts.  
               *Affected Url* : ${{ steps.alerts.outputs.repo_url }} 
               - Critical: ${{ steps.alerts.outputs.critical_alerts }}  
               - High:  ${{ steps.alerts.outputs.high_alerts }}  
               - Moderate:  ${{ steps.alerts.outputs.moderate_alerts }} 
               - Low : ${{ steps.alerts.outputs.low_alerts }}  
